// This file is auto-generated by update-codicons.js

interface Codicon {
  shortName: string;
  character: string;
  unicode: string;
  description: string;
}

const allIcons: Codicon[] = [
  {
    "shortName": "account",
    "character": "",
    "unicode": "EB99",
    "description": "person people face user contact outline"
  },
  {
    "shortName": "activate-breakpoints",
    "character": "",
    "unicode": "EA97",
    "description": "dot circle toggle switch"
  },
  {
    "shortName": "add",
    "character": "",
    "unicode": "EA60",
    "description": "combine plus add more new"
  },
  {
    "shortName": "archive",
    "character": "",
    "unicode": "EA98",
    "description": "save box delivery package"
  },
  {
    "shortName": "arrow-both",
    "character": "",
    "unicode": "EA99",
    "description": "switch swap"
  },
  {
    "shortName": "arrow-circle-down",
    "character": "",
    "unicode": "EBFC",
    "description": ""
  },
  {
    "shortName": "arrow-circle-left",
    "character": "",
    "unicode": "EBFD",
    "description": ""
  },
  {
    "shortName": "arrow-circle-right",
    "character": "",
    "unicode": "EBFE",
    "description": ""
  },
  {
    "shortName": "arrow-circle-up",
    "character": "",
    "unicode": "EBFF",
    "description": ""
  },
  {
    "shortName": "arrow-down",
    "character": "",
    "unicode": "EA9A",
    "description": ""
  },
  {
    "shortName": "arrow-left",
    "character": "",
    "unicode": "EA9B",
    "description": ""
  },
  {
    "shortName": "arrow-right",
    "character": "",
    "unicode": "EA9C",
    "description": ""
  },
  {
    "shortName": "arrow-small-down",
    "character": "",
    "unicode": "EA9D",
    "description": ""
  },
  {
    "shortName": "arrow-small-left",
    "character": "",
    "unicode": "EA9E",
    "description": ""
  },
  {
    "shortName": "arrow-small-right",
    "character": "",
    "unicode": "EA9F",
    "description": ""
  },
  {
    "shortName": "arrow-small-up",
    "character": "",
    "unicode": "EAA0",
    "description": ""
  },
  {
    "shortName": "arrow-swap",
    "character": "",
    "unicode": "EBCB",
    "description": ""
  },
  {
    "shortName": "arrow-up",
    "character": "",
    "unicode": "EAA1",
    "description": ""
  },
  {
    "shortName": "attach",
    "character": "",
    "unicode": "EC34",
    "description": ""
  },
  {
    "shortName": "azure-devops",
    "character": "",
    "unicode": "EBE8",
    "description": ""
  },
  {
    "shortName": "azure",
    "character": "",
    "unicode": "EBD8",
    "description": ""
  },
  {
    "shortName": "beaker-stop",
    "character": "",
    "unicode": "EBE1",
    "description": ""
  },
  {
    "shortName": "beaker",
    "character": "",
    "unicode": "EA79",
    "description": "test lab tube tool"
  },
  {
    "shortName": "bell-dot",
    "character": "",
    "unicode": "EB9A",
    "description": "alert notify notification"
  },
  {
    "shortName": "bell-slash-dot",
    "character": "",
    "unicode": "EC09",
    "description": ""
  },
  {
    "shortName": "bell-slash",
    "character": "",
    "unicode": "EC08",
    "description": ""
  },
  {
    "shortName": "bell",
    "character": "",
    "unicode": "EAA2",
    "description": "alert notify notification"
  },
  {
    "shortName": "blank",
    "character": "",
    "unicode": "EC03",
    "description": ""
  },
  {
    "shortName": "bold",
    "character": "",
    "unicode": "EAA3",
    "description": "text format weight font style"
  },
  {
    "shortName": "book",
    "character": "",
    "unicode": "EAA4",
    "description": "library text read open"
  },
  {
    "shortName": "bookmark",
    "character": "",
    "unicode": "EAA5",
    "description": "book save later"
  },
  {
    "shortName": "bracket-dot",
    "character": "",
    "unicode": "EBE5",
    "description": ""
  },
  {
    "shortName": "bracket-error",
    "character": "",
    "unicode": "EBE6",
    "description": ""
  },
  {
    "shortName": "briefcase",
    "character": "",
    "unicode": "EAAC",
    "description": "work workplace"
  },
  {
    "shortName": "broadcast",
    "character": "",
    "unicode": "EAAD",
    "description": "tower signal connect connection"
  },
  {
    "shortName": "browser",
    "character": "",
    "unicode": "EAAE",
    "description": "web internet page window"
  },
  {
    "shortName": "bug",
    "character": "",
    "unicode": "EAAF",
    "description": "error issue insect block"
  },
  {
    "shortName": "calendar",
    "character": "",
    "unicode": "EAB0",
    "description": "day time week month date schedule event planner"
  },
  {
    "shortName": "call-incoming",
    "character": "",
    "unicode": "EB92",
    "description": "phone cell voice connection direction"
  },
  {
    "shortName": "call-outgoing",
    "character": "",
    "unicode": "EB93",
    "description": "phone cell voice connection direction"
  },
  {
    "shortName": "case-sensitive",
    "character": "",
    "unicode": "EAB1",
    "description": "search filter option letters words"
  },
  {
    "shortName": "chat-sparkle",
    "character": "",
    "unicode": "EC4F",
    "description": ""
  },
  {
    "shortName": "check-all",
    "character": "",
    "unicode": "EBB1",
    "description": "checkmark select everything checked mark complete finish done accept approve"
  },
  {
    "shortName": "check",
    "character": "",
    "unicode": "EAB2",
    "description": "checkmark select everything checked mark complete finish done accept approve"
  },
  {
    "shortName": "checklist",
    "character": "",
    "unicode": "EAB3",
    "description": "checkmark select everything checked mark complete finish done accept todo task text"
  },
  {
    "shortName": "chevron-down",
    "character": "",
    "unicode": "EAB4",
    "description": "twistie tree node folder fold collapse"
  },
  {
    "shortName": "chevron-left",
    "character": "",
    "unicode": "EAB5",
    "description": "twistie tree node folder fold collapse"
  },
  {
    "shortName": "chevron-right",
    "character": "",
    "unicode": "EAB6",
    "description": "twistie tree node folder fold collapse"
  },
  {
    "shortName": "chevron-up",
    "character": "",
    "unicode": "EAB7",
    "description": "twistie tree node folder fold collapse"
  },
  {
    "shortName": "chip",
    "character": "",
    "unicode": "EC19",
    "description": ""
  },
  {
    "shortName": "chrome-close",
    "character": "",
    "unicode": "EAB8",
    "description": "menu bar window dismiss"
  },
  {
    "shortName": "chrome-maximize",
    "character": "",
    "unicode": "EAB9",
    "description": "menu bar window large increase"
  },
  {
    "shortName": "chrome-minimize",
    "character": "",
    "unicode": "EABA",
    "description": "menu bar window small decrease"
  },
  {
    "shortName": "chrome-restore",
    "character": "",
    "unicode": "EABB",
    "description": "menu bar window"
  },
  {
    "shortName": "circle-filled",
    "character": "",
    "unicode": "EA71",
    "description": "dot round small bullet breakpoint"
  },
  {
    "shortName": "circle-large-filled",
    "character": "",
    "unicode": "EBB4",
    "description": "dot round bullet"
  },
  {
    "shortName": "circle-large",
    "character": "",
    "unicode": "EBB5",
    "description": "dot round bullet"
  },
  {
    "shortName": "circle-slash",
    "character": "",
    "unicode": "EABD",
    "description": "error block stop disable"
  },
  {
    "shortName": "circle-small-filled",
    "character": "",
    "unicode": "EB8A",
    "description": ""
  },
  {
    "shortName": "circle-small",
    "character": "",
    "unicode": "EC07",
    "description": ""
  },
  {
    "shortName": "circle",
    "character": "",
    "unicode": "EABC",
    "description": "dot round small bullet unverified breakpoint"
  },
  {
    "shortName": "circuit-board",
    "character": "",
    "unicode": "EABE",
    "description": "iot device process lines"
  },
  {
    "shortName": "clear-all",
    "character": "",
    "unicode": "EABF",
    "description": "reset remove"
  },
  {
    "shortName": "clippy",
    "character": "",
    "unicode": "EAC0",
    "description": "clipboard document edit copy"
  },
  {
    "shortName": "close-all",
    "character": "",
    "unicode": "EAC1",
    "description": "remove bulk"
  },
  {
    "shortName": "close",
    "character": "",
    "unicode": "EA76",
    "description": "remove x cancel stop miltiply"
  },
  {
    "shortName": "cloud-download",
    "character": "",
    "unicode": "EAC2",
    "description": "install import"
  },
  {
    "shortName": "cloud-upload",
    "character": "",
    "unicode": "EAC3",
    "description": "export"
  },
  {
    "shortName": "cloud",
    "character": "",
    "unicode": "EBAA",
    "description": "online service"
  },
  {
    "shortName": "code-oss",
    "character": "",
    "unicode": "EC2B",
    "description": ""
  },
  {
    "shortName": "code-review",
    "character": "",
    "unicode": "EC37",
    "description": ""
  },
  {
    "shortName": "code",
    "character": "",
    "unicode": "EAC4",
    "description": "embed script programming server"
  },
  {
    "shortName": "coffee",
    "character": "",
    "unicode": "EC15",
    "description": ""
  },
  {
    "shortName": "collapse-all",
    "character": "",
    "unicode": "EAC5",
    "description": "bulk fold minimize"
  },
  {
    "shortName": "color-mode",
    "character": "",
    "unicode": "EAC6",
    "description": "switch dark light contrast mode toggle"
  },
  {
    "shortName": "combine",
    "character": "",
    "unicode": "EBB6",
    "description": ""
  },
  {
    "shortName": "comment-discussion",
    "character": "",
    "unicode": "EAC7",
    "description": "dialog message bubble chat"
  },
  {
    "shortName": "comment-draft",
    "character": "",
    "unicode": "EC0E",
    "description": ""
  },
  {
    "shortName": "comment-unresolved",
    "character": "",
    "unicode": "EC0A",
    "description": ""
  },
  {
    "shortName": "comment",
    "character": "",
    "unicode": "EA6B",
    "description": "dialog message bubble chat"
  },
  {
    "shortName": "compass-active",
    "character": "",
    "unicode": "EBD7",
    "description": ""
  },
  {
    "shortName": "compass-dot",
    "character": "",
    "unicode": "EBD6",
    "description": ""
  },
  {
    "shortName": "compass",
    "character": "",
    "unicode": "EBD5",
    "description": ""
  },
  {
    "shortName": "copilot-blocked",
    "character": "",
    "unicode": "EC3D",
    "description": ""
  },
  {
    "shortName": "copilot-error",
    "character": "",
    "unicode": "EC4D",
    "description": ""
  },
  {
    "shortName": "copilot-in-progress",
    "character": "",
    "unicode": "EC4C",
    "description": ""
  },
  {
    "shortName": "copilot-large",
    "character": "",
    "unicode": "EC3A",
    "description": ""
  },
  {
    "shortName": "copilot-not-connected",
    "character": "",
    "unicode": "EC3E",
    "description": ""
  },
  {
    "shortName": "copilot-snooze",
    "character": "",
    "unicode": "EC52",
    "description": ""
  },
  {
    "shortName": "copilot-success",
    "character": "",
    "unicode": "EC4E",
    "description": ""
  },
  {
    "shortName": "copilot-unavailable",
    "character": "",
    "unicode": "EC42",
    "description": ""
  },
  {
    "shortName": "copilot-warning-large",
    "character": "",
    "unicode": "EC3B",
    "description": ""
  },
  {
    "shortName": "copilot-warning",
    "character": "",
    "unicode": "EC38",
    "description": ""
  },
  {
    "shortName": "copilot",
    "character": "",
    "unicode": "EC1E",
    "description": ""
  },
  {
    "shortName": "copy",
    "character": "",
    "unicode": "EBCC",
    "description": ""
  },
  {
    "shortName": "coverage",
    "character": "",
    "unicode": "EC2E",
    "description": ""
  },
  {
    "shortName": "credit-card",
    "character": "",
    "unicode": "EAC9",
    "description": "payment merchant money"
  },
  {
    "shortName": "dash",
    "character": "",
    "unicode": "EACC",
    "description": "line minus subtract hyphen"
  },
  {
    "shortName": "dashboard",
    "character": "",
    "unicode": "EACD",
    "description": "panel stats dial"
  },
  {
    "shortName": "database",
    "character": "",
    "unicode": "EACE",
    "description": "sql db storage online cloud"
  },
  {
    "shortName": "debug-all",
    "character": "",
    "unicode": "EBDC",
    "description": ""
  },
  {
    "shortName": "debug-alt-small",
    "character": "",
    "unicode": "EBA8",
    "description": "run"
  },
  {
    "shortName": "debug-alt",
    "character": "",
    "unicode": "EB91",
    "description": "run"
  },
  {
    "shortName": "debug-breakpoint-conditional-unverified",
    "character": "",
    "unicode": "EAA6",
    "description": ""
  },
  {
    "shortName": "debug-breakpoint-conditional",
    "character": "",
    "unicode": "EAA7",
    "description": ""
  },
  {
    "shortName": "debug-breakpoint-data-unverified",
    "character": "",
    "unicode": "EAA8",
    "description": ""
  },
  {
    "shortName": "debug-breakpoint-data",
    "character": "",
    "unicode": "EAA9",
    "description": ""
  },
  {
    "shortName": "debug-breakpoint-function-unverified",
    "character": "",
    "unicode": "EB87",
    "description": ""
  },
  {
    "shortName": "debug-breakpoint-function",
    "character": "",
    "unicode": "EB88",
    "description": ""
  },
  {
    "shortName": "debug-breakpoint-log-unverified",
    "character": "",
    "unicode": "EAAA",
    "description": ""
  },
  {
    "shortName": "debug-breakpoint-log",
    "character": "",
    "unicode": "EAAB",
    "description": ""
  },
  {
    "shortName": "debug-breakpoint-unsupported",
    "character": "",
    "unicode": "EB8C",
    "description": ""
  },
  {
    "shortName": "debug-console",
    "character": "",
    "unicode": "EB9B",
    "description": "terminal command input compile build"
  },
  {
    "shortName": "debug-continue-small",
    "character": "",
    "unicode": "EBE0",
    "description": ""
  },
  {
    "shortName": "debug-continue",
    "character": "",
    "unicode": "EACF",
    "description": ""
  },
  {
    "shortName": "debug-coverage",
    "character": "",
    "unicode": "EBDD",
    "description": ""
  },
  {
    "shortName": "debug-disconnect",
    "character": "",
    "unicode": "EAD0",
    "description": "stop unplug eject"
  },
  {
    "shortName": "debug-line-by-line",
    "character": "",
    "unicode": "EBD0",
    "description": ""
  },
  {
    "shortName": "debug-pause",
    "character": "",
    "unicode": "EAD1",
    "description": ""
  },
  {
    "shortName": "debug-rerun",
    "character": "",
    "unicode": "EBC0",
    "description": ""
  },
  {
    "shortName": "debug-restart-frame",
    "character": "",
    "unicode": "EB90",
    "description": ""
  },
  {
    "shortName": "debug-restart",
    "character": "",
    "unicode": "EAD2",
    "description": ""
  },
  {
    "shortName": "debug-reverse-continue",
    "character": "",
    "unicode": "EB8E",
    "description": ""
  },
  {
    "shortName": "debug-stackframe-active",
    "character": "",
    "unicode": "EB89",
    "description": ""
  },
  {
    "shortName": "debug-stackframe",
    "character": "",
    "unicode": "EB8B",
    "description": ""
  },
  {
    "shortName": "debug-start",
    "character": "",
    "unicode": "EAD3",
    "description": ""
  },
  {
    "shortName": "debug-step-back",
    "character": "",
    "unicode": "EB8F",
    "description": ""
  },
  {
    "shortName": "debug-step-into",
    "character": "",
    "unicode": "EAD4",
    "description": ""
  },
  {
    "shortName": "debug-step-out",
    "character": "",
    "unicode": "EAD5",
    "description": ""
  },
  {
    "shortName": "debug-step-over",
    "character": "",
    "unicode": "EAD6",
    "description": ""
  },
  {
    "shortName": "debug-stop",
    "character": "",
    "unicode": "EAD7",
    "description": ""
  },
  {
    "shortName": "debug",
    "character": "",
    "unicode": "EAD8",
    "description": ""
  },
  {
    "shortName": "desktop-download",
    "character": "",
    "unicode": "EA78",
    "description": "install"
  },
  {
    "shortName": "device-camera-video",
    "character": "",
    "unicode": "EAD9",
    "description": "movie record capture"
  },
  {
    "shortName": "device-camera",
    "character": "",
    "unicode": "EADA",
    "description": "capture picture image"
  },
  {
    "shortName": "device-mobile",
    "character": "",
    "unicode": "EADB",
    "description": "phone handheld smartphone"
  },
  {
    "shortName": "diff-added",
    "character": "",
    "unicode": "EADC",
    "description": "git change"
  },
  {
    "shortName": "diff-ignored",
    "character": "",
    "unicode": "EADD",
    "description": "git change"
  },
  {
    "shortName": "diff-modified",
    "character": "",
    "unicode": "EADE",
    "description": "git change"
  },
  {
    "shortName": "diff-multiple",
    "character": "",
    "unicode": "EC23",
    "description": ""
  },
  {
    "shortName": "diff-removed",
    "character": "",
    "unicode": "EADF",
    "description": "git change"
  },
  {
    "shortName": "diff-renamed",
    "character": "",
    "unicode": "EAE0",
    "description": "git change"
  },
  {
    "shortName": "diff-single",
    "character": "",
    "unicode": "EB43",
    "description": ""
  },
  {
    "shortName": "diff",
    "character": "",
    "unicode": "EAE1",
    "description": ""
  },
  {
    "shortName": "discard",
    "character": "",
    "unicode": "EAE2",
    "description": ""
  },
  {
    "shortName": "edit-session",
    "character": "",
    "unicode": "EC36",
    "description": ""
  },
  {
    "shortName": "edit-sparkle",
    "character": "",
    "unicode": "EC51",
    "description": ""
  },
  {
    "shortName": "edit",
    "character": "",
    "unicode": "EA73",
    "description": ""
  },
  {
    "shortName": "editor-layout",
    "character": "",
    "unicode": "EAE3",
    "description": ""
  },
  {
    "shortName": "ellipsis",
    "character": "",
    "unicode": "EA7C",
    "description": ""
  },
  {
    "shortName": "empty-window",
    "character": "",
    "unicode": "EAE4",
    "description": ""
  },
  {
    "shortName": "error-small",
    "character": "",
    "unicode": "EBFB",
    "description": ""
  },
  {
    "shortName": "error",
    "character": "",
    "unicode": "EA87",
    "description": ""
  },
  {
    "shortName": "exclude",
    "character": "",
    "unicode": "EAE5",
    "description": ""
  },
  {
    "shortName": "expand-all",
    "character": "",
    "unicode": "EB95",
    "description": ""
  },
  {
    "shortName": "export",
    "character": "",
    "unicode": "EBAC",
    "description": ""
  },
  {
    "shortName": "extensions-large",
    "character": "",
    "unicode": "EC48",
    "description": ""
  },
  {
    "shortName": "extensions",
    "character": "",
    "unicode": "EAE6",
    "description": ""
  },
  {
    "shortName": "eye-closed",
    "character": "",
    "unicode": "EAE7",
    "description": ""
  },
  {
    "shortName": "eye",
    "character": "",
    "unicode": "EA70",
    "description": ""
  },
  {
    "shortName": "feedback",
    "character": "",
    "unicode": "EB96",
    "description": ""
  },
  {
    "shortName": "file-binary",
    "character": "",
    "unicode": "EAE8",
    "description": ""
  },
  {
    "shortName": "file-code",
    "character": "",
    "unicode": "EAE9",
    "description": ""
  },
  {
    "shortName": "file-media",
    "character": "",
    "unicode": "EAEA",
    "description": ""
  },
  {
    "shortName": "file-pdf",
    "character": "",
    "unicode": "EAEB",
    "description": ""
  },
  {
    "shortName": "file-submodule",
    "character": "",
    "unicode": "EAEC",
    "description": ""
  },
  {
    "shortName": "file-symlink-directory",
    "character": "",
    "unicode": "EAED",
    "description": ""
  },
  {
    "shortName": "file-symlink-file",
    "character": "",
    "unicode": "EAEE",
    "description": ""
  },
  {
    "shortName": "file-zip",
    "character": "",
    "unicode": "EAEF",
    "description": ""
  },
  {
    "shortName": "file",
    "character": "",
    "unicode": "EA7B",
    "description": ""
  },
  {
    "shortName": "files",
    "character": "",
    "unicode": "EAF0",
    "description": ""
  },
  {
    "shortName": "filter-filled",
    "character": "",
    "unicode": "EBCE",
    "description": ""
  },
  {
    "shortName": "filter",
    "character": "",
    "unicode": "EAF1",
    "description": ""
  },
  {
    "shortName": "flag",
    "character": "",
    "unicode": "EC3F",
    "description": ""
  },
  {
    "shortName": "flame",
    "character": "",
    "unicode": "EAF2",
    "description": ""
  },
  {
    "shortName": "fold-down",
    "character": "",
    "unicode": "EAF3",
    "description": ""
  },
  {
    "shortName": "fold-up",
    "character": "",
    "unicode": "EAF4",
    "description": ""
  },
  {
    "shortName": "fold",
    "character": "",
    "unicode": "EAF5",
    "description": ""
  },
  {
    "shortName": "folder-active",
    "character": "",
    "unicode": "EAF6",
    "description": ""
  },
  {
    "shortName": "folder-library",
    "character": "",
    "unicode": "EBDF",
    "description": ""
  },
  {
    "shortName": "folder-opened",
    "character": "",
    "unicode": "EAF7",
    "description": ""
  },
  {
    "shortName": "folder",
    "character": "",
    "unicode": "EA83",
    "description": ""
  },
  {
    "shortName": "game",
    "character": "",
    "unicode": "EC17",
    "description": ""
  },
  {
    "shortName": "gear",
    "character": "",
    "unicode": "EAF8",
    "description": ""
  },
  {
    "shortName": "gift",
    "character": "",
    "unicode": "EAF9",
    "description": ""
  },
  {
    "shortName": "gist-secret",
    "character": "",
    "unicode": "EAFA",
    "description": ""
  },
  {
    "shortName": "gist",
    "character": "",
    "unicode": "EAFB",
    "description": ""
  },
  {
    "shortName": "git-commit",
    "character": "",
    "unicode": "EAFC",
    "description": ""
  },
  {
    "shortName": "git-compare",
    "character": "",
    "unicode": "EAFD",
    "description": ""
  },
  {
    "shortName": "git-fetch",
    "character": "",
    "unicode": "F101",
    "description": ""
  },
  {
    "shortName": "git-merge",
    "character": "",
    "unicode": "EAFE",
    "description": ""
  },
  {
    "shortName": "git-pull-request-closed",
    "character": "",
    "unicode": "EBDA",
    "description": ""
  },
  {
    "shortName": "git-pull-request-create",
    "character": "",
    "unicode": "EBBC",
    "description": ""
  },
  {
    "shortName": "git-pull-request-done",
    "character": "",
    "unicode": "EC46",
    "description": ""
  },
  {
    "shortName": "git-pull-request-draft",
    "character": "",
    "unicode": "EBDB",
    "description": ""
  },
  {
    "shortName": "git-pull-request-go-to-changes",
    "character": "",
    "unicode": "EC0B",
    "description": ""
  },
  {
    "shortName": "git-pull-request-new-changes",
    "character": "",
    "unicode": "EC0C",
    "description": ""
  },
  {
    "shortName": "git-pull-request",
    "character": "",
    "unicode": "EA64",
    "description": ""
  },
  {
    "shortName": "git-stash-apply",
    "character": "",
    "unicode": "EC27",
    "description": ""
  },
  {
    "shortName": "git-stash-pop",
    "character": "",
    "unicode": "EC28",
    "description": ""
  },
  {
    "shortName": "git-stash",
    "character": "",
    "unicode": "EC26",
    "description": ""
  },
  {
    "shortName": "github-action",
    "character": "",
    "unicode": "EAFF",
    "description": ""
  },
  {
    "shortName": "github-alt",
    "character": "",
    "unicode": "EB00",
    "description": ""
  },
  {
    "shortName": "github-inverted",
    "character": "",
    "unicode": "EBA1",
    "description": ""
  },
  {
    "shortName": "github-project",
    "character": "",
    "unicode": "EC2F",
    "description": ""
  },
  {
    "shortName": "github",
    "character": "",
    "unicode": "EA84",
    "description": ""
  },
  {
    "shortName": "globe",
    "character": "",
    "unicode": "EB01",
    "description": ""
  },
  {
    "shortName": "go-to-editing-session",
    "character": "",
    "unicode": "EC35",
    "description": ""
  },
  {
    "shortName": "go-to-file",
    "character": "",
    "unicode": "EA94",
    "description": ""
  },
  {
    "shortName": "go-to-search",
    "character": "",
    "unicode": "EC32",
    "description": ""
  },
  {
    "shortName": "grabber",
    "character": "",
    "unicode": "EB02",
    "description": ""
  },
  {
    "shortName": "graph-left",
    "character": "",
    "unicode": "EBAD",
    "description": ""
  },
  {
    "shortName": "graph-line",
    "character": "",
    "unicode": "EBE2",
    "description": ""
  },
  {
    "shortName": "graph-scatter",
    "character": "",
    "unicode": "EBE3",
    "description": ""
  },
  {
    "shortName": "graph",
    "character": "",
    "unicode": "EB03",
    "description": ""
  },
  {
    "shortName": "gripper",
    "character": "",
    "unicode": "EB04",
    "description": ""
  },
  {
    "shortName": "group-by-ref-type",
    "character": "",
    "unicode": "EB97",
    "description": ""
  },
  {
    "shortName": "heart-filled",
    "character": "",
    "unicode": "EC04",
    "description": ""
  },
  {
    "shortName": "heart",
    "character": "",
    "unicode": "EB05",
    "description": ""
  },
  {
    "shortName": "history",
    "character": "",
    "unicode": "EA82",
    "description": ""
  },
  {
    "shortName": "home",
    "character": "",
    "unicode": "EB06",
    "description": ""
  },
  {
    "shortName": "horizontal-rule",
    "character": "",
    "unicode": "EB07",
    "description": ""
  },
  {
    "shortName": "hubot",
    "character": "",
    "unicode": "EB08",
    "description": ""
  },
  {
    "shortName": "inbox",
    "character": "",
    "unicode": "EB09",
    "description": ""
  },
  {
    "shortName": "indent",
    "character": "",
    "unicode": "EBF9",
    "description": ""
  },
  {
    "shortName": "info",
    "character": "",
    "unicode": "EA74",
    "description": ""
  },
  {
    "shortName": "insert",
    "character": "",
    "unicode": "EC11",
    "description": ""
  },
  {
    "shortName": "inspect",
    "character": "",
    "unicode": "EBD1",
    "description": ""
  },
  {
    "shortName": "issue-draft",
    "character": "",
    "unicode": "EBD9",
    "description": ""
  },
  {
    "shortName": "issue-reopened",
    "character": "",
    "unicode": "EB0B",
    "description": ""
  },
  {
    "shortName": "issues",
    "character": "",
    "unicode": "EB0C",
    "description": ""
  },
  {
    "shortName": "italic",
    "character": "",
    "unicode": "EB0D",
    "description": ""
  },
  {
    "shortName": "jersey",
    "character": "",
    "unicode": "EB0E",
    "description": ""
  },
  {
    "shortName": "json",
    "character": "",
    "unicode": "EB0F",
    "description": ""
  },
  {
    "shortName": "kebab-vertical",
    "character": "",
    "unicode": "EB10",
    "description": ""
  },
  {
    "shortName": "key",
    "character": "",
    "unicode": "EB11",
    "description": ""
  },
  {
    "shortName": "keyboard-tab-above",
    "character": "",
    "unicode": "EC44",
    "description": ""
  },
  {
    "shortName": "keyboard-tab-below",
    "character": "",
    "unicode": "EC45",
    "description": ""
  },
  {
    "shortName": "keyboard-tab",
    "character": "",
    "unicode": "EC3C",
    "description": ""
  },
  {
    "shortName": "law",
    "character": "",
    "unicode": "EB12",
    "description": ""
  },
  {
    "shortName": "layers-active",
    "character": "",
    "unicode": "EBD4",
    "description": ""
  },
  {
    "shortName": "layers-dot",
    "character": "",
    "unicode": "EBD3",
    "description": ""
  },
  {
    "shortName": "layers",
    "character": "",
    "unicode": "EBD2",
    "description": ""
  },
  {
    "shortName": "layout-activitybar-left",
    "character": "",
    "unicode": "EBEC",
    "description": ""
  },
  {
    "shortName": "layout-activitybar-right",
    "character": "",
    "unicode": "EBED",
    "description": ""
  },
  {
    "shortName": "layout-centered",
    "character": "",
    "unicode": "EBF7",
    "description": ""
  },
  {
    "shortName": "layout-menubar",
    "character": "",
    "unicode": "EBF6",
    "description": ""
  },
  {
    "shortName": "layout-panel-center",
    "character": "",
    "unicode": "EBEF",
    "description": ""
  },
  {
    "shortName": "layout-panel-dock",
    "character": "",
    "unicode": "EC49",
    "description": ""
  },
  {
    "shortName": "layout-panel-justify",
    "character": "",
    "unicode": "EBF0",
    "description": ""
  },
  {
    "shortName": "layout-panel-left",
    "character": "",
    "unicode": "EBEE",
    "description": ""
  },
  {
    "shortName": "layout-panel-off",
    "character": "",
    "unicode": "EC01",
    "description": ""
  },
  {
    "shortName": "layout-panel-right",
    "character": "",
    "unicode": "EBF1",
    "description": ""
  },
  {
    "shortName": "layout-panel",
    "character": "",
    "unicode": "EBF2",
    "description": ""
  },
  {
    "shortName": "layout-sidebar-left-dock",
    "character": "",
    "unicode": "EC4A",
    "description": ""
  },
  {
    "shortName": "layout-sidebar-left-off",
    "character": "",
    "unicode": "EC02",
    "description": ""
  },
  {
    "shortName": "layout-sidebar-left",
    "character": "",
    "unicode": "EBF3",
    "description": ""
  },
  {
    "shortName": "layout-sidebar-right-dock",
    "character": "",
    "unicode": "EC4B",
    "description": ""
  },
  {
    "shortName": "layout-sidebar-right-off",
    "character": "",
    "unicode": "EC00",
    "description": ""
  },
  {
    "shortName": "layout-sidebar-right",
    "character": "",
    "unicode": "EBF4",
    "description": ""
  },
  {
    "shortName": "layout-statusbar",
    "character": "",
    "unicode": "EBF5",
    "description": ""
  },
  {
    "shortName": "layout",
    "character": "",
    "unicode": "EBEB",
    "description": ""
  },
  {
    "shortName": "library",
    "character": "",
    "unicode": "EB9C",
    "description": ""
  },
  {
    "shortName": "lightbulb-autofix",
    "character": "",
    "unicode": "EB13",
    "description": ""
  },
  {
    "shortName": "lightbulb-empty",
    "character": "",
    "unicode": "EC40",
    "description": ""
  },
  {
    "shortName": "lightbulb-sparkle",
    "character": "",
    "unicode": "EC1F",
    "description": ""
  },
  {
    "shortName": "lightbulb",
    "character": "",
    "unicode": "EA61",
    "description": ""
  },
  {
    "shortName": "link-external",
    "character": "",
    "unicode": "EB14",
    "description": ""
  },
  {
    "shortName": "link",
    "character": "",
    "unicode": "EB15",
    "description": ""
  },
  {
    "shortName": "list-filter",
    "character": "",
    "unicode": "EB83",
    "description": ""
  },
  {
    "shortName": "list-flat",
    "character": "",
    "unicode": "EB84",
    "description": ""
  },
  {
    "shortName": "list-ordered",
    "character": "",
    "unicode": "EB16",
    "description": ""
  },
  {
    "shortName": "list-selection",
    "character": "",
    "unicode": "EB85",
    "description": ""
  },
  {
    "shortName": "list-tree",
    "character": "",
    "unicode": "EB86",
    "description": ""
  },
  {
    "shortName": "list-unordered",
    "character": "",
    "unicode": "EB17",
    "description": ""
  },
  {
    "shortName": "live-share",
    "character": "",
    "unicode": "EB18",
    "description": ""
  },
  {
    "shortName": "loading",
    "character": "",
    "unicode": "EB19",
    "description": ""
  },
  {
    "shortName": "location",
    "character": "",
    "unicode": "EB1A",
    "description": ""
  },
  {
    "shortName": "lock-small",
    "character": "",
    "unicode": "EBE7",
    "description": ""
  },
  {
    "shortName": "lock",
    "character": "",
    "unicode": "EA75",
    "description": ""
  },
  {
    "shortName": "magnet",
    "character": "",
    "unicode": "EBAE",
    "description": ""
  },
  {
    "shortName": "mail-read",
    "character": "",
    "unicode": "EB1B",
    "description": ""
  },
  {
    "shortName": "mail",
    "character": "",
    "unicode": "EB1C",
    "description": ""
  },
  {
    "shortName": "map-filled",
    "character": "",
    "unicode": "EC06",
    "description": ""
  },
  {
    "shortName": "map-vertical-filled",
    "character": "",
    "unicode": "EC31",
    "description": ""
  },
  {
    "shortName": "map-vertical",
    "character": "",
    "unicode": "EC30",
    "description": ""
  },
  {
    "shortName": "map",
    "character": "",
    "unicode": "EC05",
    "description": ""
  },
  {
    "shortName": "markdown",
    "character": "",
    "unicode": "EB1D",
    "description": ""
  },
  {
    "shortName": "mcp",
    "character": "",
    "unicode": "EC47",
    "description": ""
  },
  {
    "shortName": "megaphone",
    "character": "",
    "unicode": "EB1E",
    "description": ""
  },
  {
    "shortName": "mention",
    "character": "",
    "unicode": "EB1F",
    "description": ""
  },
  {
    "shortName": "menu",
    "character": "",
    "unicode": "EB94",
    "description": ""
  },
  {
    "shortName": "merge",
    "character": "",
    "unicode": "EBAB",
    "description": ""
  },
  {
    "shortName": "mic-filled",
    "character": "",
    "unicode": "EC1C",
    "description": ""
  },
  {
    "shortName": "mic",
    "character": "",
    "unicode": "EC12",
    "description": ""
  },
  {
    "shortName": "milestone",
    "character": "",
    "unicode": "EB20",
    "description": ""
  },
  {
    "shortName": "mirror",
    "character": "",
    "unicode": "EA69",
    "description": ""
  },
  {
    "shortName": "mortar-board",
    "character": "",
    "unicode": "EB21",
    "description": ""
  },
  {
    "shortName": "move",
    "character": "",
    "unicode": "EB22",
    "description": ""
  },
  {
    "shortName": "multiple-windows",
    "character": "",
    "unicode": "EB23",
    "description": ""
  },
  {
    "shortName": "music",
    "character": "",
    "unicode": "EC1B",
    "description": ""
  },
  {
    "shortName": "mute",
    "character": "",
    "unicode": "EB24",
    "description": ""
  },
  {
    "shortName": "new-file",
    "character": "",
    "unicode": "EA7F",
    "description": ""
  },
  {
    "shortName": "new-folder",
    "character": "",
    "unicode": "EA80",
    "description": ""
  },
  {
    "shortName": "newline",
    "character": "",
    "unicode": "EBEA",
    "description": ""
  },
  {
    "shortName": "no-newline",
    "character": "",
    "unicode": "EB25",
    "description": ""
  },
  {
    "shortName": "note",
    "character": "",
    "unicode": "EB26",
    "description": ""
  },
  {
    "shortName": "notebook-template",
    "character": "",
    "unicode": "EBBF",
    "description": ""
  },
  {
    "shortName": "notebook",
    "character": "",
    "unicode": "EBAF",
    "description": ""
  },
  {
    "shortName": "octoface",
    "character": "",
    "unicode": "EB27",
    "description": ""
  },
  {
    "shortName": "open-preview",
    "character": "",
    "unicode": "EB28",
    "description": ""
  },
  {
    "shortName": "organization",
    "character": "",
    "unicode": "EA7E",
    "description": ""
  },
  {
    "shortName": "output",
    "character": "",
    "unicode": "EB9D",
    "description": ""
  },
  {
    "shortName": "package",
    "character": "",
    "unicode": "EB29",
    "description": ""
  },
  {
    "shortName": "paintcan",
    "character": "",
    "unicode": "EB2A",
    "description": ""
  },
  {
    "shortName": "pass-filled",
    "character": "",
    "unicode": "EBB3",
    "description": "play check checkmark filled issue closed"
  },
  {
    "shortName": "pass",
    "character": "",
    "unicode": "EBA4",
    "description": "play check checkmark outline issue closed"
  },
  {
    "shortName": "percentage",
    "character": "",
    "unicode": "EC33",
    "description": ""
  },
  {
    "shortName": "person-add",
    "character": "",
    "unicode": "EBCD",
    "description": ""
  },
  {
    "shortName": "person",
    "character": "",
    "unicode": "EA67",
    "description": ""
  },
  {
    "shortName": "piano",
    "character": "",
    "unicode": "EC1A",
    "description": ""
  },
  {
    "shortName": "pie-chart",
    "character": "",
    "unicode": "EBE4",
    "description": ""
  },
  {
    "shortName": "pin",
    "character": "",
    "unicode": "EB2B",
    "description": ""
  },
  {
    "shortName": "pinned-dirty",
    "character": "",
    "unicode": "EBB2",
    "description": ""
  },
  {
    "shortName": "pinned",
    "character": "",
    "unicode": "EBA0",
    "description": ""
  },
  {
    "shortName": "play-circle",
    "character": "",
    "unicode": "EBA6",
    "description": "run"
  },
  {
    "shortName": "play",
    "character": "",
    "unicode": "EB2C",
    "description": "run"
  },
  {
    "shortName": "plug",
    "character": "",
    "unicode": "EB2D",
    "description": ""
  },
  {
    "shortName": "preserve-case",
    "character": "",
    "unicode": "EB2E",
    "description": ""
  },
  {
    "shortName": "preview",
    "character": "",
    "unicode": "EB2F",
    "description": ""
  },
  {
    "shortName": "primitive-square",
    "character": "",
    "unicode": "EA72",
    "description": ""
  },
  {
    "shortName": "project",
    "character": "",
    "unicode": "EB30",
    "description": ""
  },
  {
    "shortName": "pulse",
    "character": "",
    "unicode": "EB31",
    "description": ""
  },
  {
    "shortName": "python",
    "character": "",
    "unicode": "EC39",
    "description": ""
  },
  {
    "shortName": "question",
    "character": "",
    "unicode": "EB32",
    "description": ""
  },
  {
    "shortName": "quote",
    "character": "",
    "unicode": "EB33",
    "description": ""
  },
  {
    "shortName": "radio-tower",
    "character": "",
    "unicode": "EB34",
    "description": ""
  },
  {
    "shortName": "reactions",
    "character": "",
    "unicode": "EB35",
    "description": ""
  },
  {
    "shortName": "record-keys",
    "character": "",
    "unicode": "EA65",
    "description": ""
  },
  {
    "shortName": "record-small",
    "character": "",
    "unicode": "EBFA",
    "description": ""
  },
  {
    "shortName": "record",
    "character": "",
    "unicode": "EBA7",
    "description": ""
  },
  {
    "shortName": "redo",
    "character": "",
    "unicode": "EBB0",
    "description": ""
  },
  {
    "shortName": "references",
    "character": "",
    "unicode": "EB36",
    "description": ""
  },
  {
    "shortName": "refresh",
    "character": "",
    "unicode": "EB37",
    "description": ""
  },
  {
    "shortName": "regex",
    "character": "",
    "unicode": "EB38",
    "description": ""
  },
  {
    "shortName": "remote-explorer",
    "character": "",
    "unicode": "EB39",
    "description": ""
  },
  {
    "shortName": "remote",
    "character": "",
    "unicode": "EB3A",
    "description": ""
  },
  {
    "shortName": "remove",
    "character": "",
    "unicode": "EB3B",
    "description": ""
  },
  {
    "shortName": "replace-all",
    "character": "",
    "unicode": "EB3C",
    "description": ""
  },
  {
    "shortName": "replace",
    "character": "",
    "unicode": "EB3D",
    "description": ""
  },
  {
    "shortName": "reply",
    "character": "",
    "unicode": "EA7D",
    "description": ""
  },
  {
    "shortName": "repo-clone",
    "character": "",
    "unicode": "EB3E",
    "description": ""
  },
  {
    "shortName": "repo-fetch",
    "character": "",
    "unicode": "EC1D",
    "description": ""
  },
  {
    "shortName": "repo-force-push",
    "character": "",
    "unicode": "EB3F",
    "description": ""
  },
  {
    "shortName": "repo-forked",
    "character": "",
    "unicode": "EA63",
    "description": ""
  },
  {
    "shortName": "repo-pinned",
    "character": "",
    "unicode": "EC43",
    "description": ""
  },
  {
    "shortName": "repo-pull",
    "character": "",
    "unicode": "EB40",
    "description": ""
  },
  {
    "shortName": "repo-push",
    "character": "",
    "unicode": "EB41",
    "description": ""
  },
  {
    "shortName": "repo",
    "character": "",
    "unicode": "EA62",
    "description": ""
  },
  {
    "shortName": "report",
    "character": "",
    "unicode": "EB42",
    "description": ""
  },
  {
    "shortName": "robot",
    "character": "",
    "unicode": "EC20",
    "description": ""
  },
  {
    "shortName": "rocket",
    "character": "",
    "unicode": "EB44",
    "description": ""
  },
  {
    "shortName": "root-folder-opened",
    "character": "",
    "unicode": "EB45",
    "description": ""
  },
  {
    "shortName": "root-folder",
    "character": "",
    "unicode": "EB46",
    "description": ""
  },
  {
    "shortName": "rss",
    "character": "",
    "unicode": "EB47",
    "description": ""
  },
  {
    "shortName": "ruby",
    "character": "",
    "unicode": "EB48",
    "description": ""
  },
  {
    "shortName": "run-above",
    "character": "",
    "unicode": "EBBD",
    "description": ""
  },
  {
    "shortName": "run-all-coverage",
    "character": "",
    "unicode": "EC2D",
    "description": ""
  },
  {
    "shortName": "run-all",
    "character": "",
    "unicode": "EB9E",
    "description": ""
  },
  {
    "shortName": "run-below",
    "character": "",
    "unicode": "EBBE",
    "description": ""
  },
  {
    "shortName": "run-coverage",
    "character": "",
    "unicode": "EC2C",
    "description": ""
  },
  {
    "shortName": "run-errors",
    "character": "",
    "unicode": "EBDE",
    "description": ""
  },
  {
    "shortName": "save-all",
    "character": "",
    "unicode": "EB49",
    "description": ""
  },
  {
    "shortName": "save-as",
    "character": "",
    "unicode": "EB4A",
    "description": ""
  },
  {
    "shortName": "save",
    "character": "",
    "unicode": "EB4B",
    "description": ""
  },
  {
    "shortName": "screen-full",
    "character": "",
    "unicode": "EB4C",
    "description": ""
  },
  {
    "shortName": "screen-normal",
    "character": "",
    "unicode": "EB4D",
    "description": ""
  },
  {
    "shortName": "search-fuzzy",
    "character": "",
    "unicode": "EC0D",
    "description": ""
  },
  {
    "shortName": "search-sparkle",
    "character": "",
    "unicode": "EC50",
    "description": ""
  },
  {
    "shortName": "search-stop",
    "character": "",
    "unicode": "EB4E",
    "description": ""
  },
  {
    "shortName": "search",
    "character": "",
    "unicode": "EA6D",
    "description": ""
  },
  {
    "shortName": "send",
    "character": "",
    "unicode": "EC0F",
    "description": ""
  },
  {
    "shortName": "server-environment",
    "character": "",
    "unicode": "EBA3",
    "description": ""
  },
  {
    "shortName": "server-process",
    "character": "",
    "unicode": "EBA2",
    "description": ""
  },
  {
    "shortName": "server",
    "character": "",
    "unicode": "EB50",
    "description": ""
  },
  {
    "shortName": "settings-gear",
    "character": "",
    "unicode": "EB51",
    "description": ""
  },
  {
    "shortName": "settings",
    "character": "",
    "unicode": "EB52",
    "description": ""
  },
  {
    "shortName": "share",
    "character": "",
    "unicode": "EC25",
    "description": ""
  },
  {
    "shortName": "shield",
    "character": "",
    "unicode": "EB53",
    "description": ""
  },
  {
    "shortName": "sign-in",
    "character": "",
    "unicode": "EA6F",
    "description": ""
  },
  {
    "shortName": "sign-out",
    "character": "",
    "unicode": "EA6E",
    "description": ""
  },
  {
    "shortName": "smiley",
    "character": "",
    "unicode": "EB54",
    "description": ""
  },
  {
    "shortName": "snake",
    "character": "",
    "unicode": "EC16",
    "description": ""
  },
  {
    "shortName": "sort-precedence",
    "character": "",
    "unicode": "EB55",
    "description": ""
  },
  {
    "shortName": "source-control",
    "character": "",
    "unicode": "EA68",
    "description": ""
  },
  {
    "shortName": "sparkle-filled",
    "character": "",
    "unicode": "EC21",
    "description": ""
  },
  {
    "shortName": "sparkle",
    "character": "",
    "unicode": "EC10",
    "description": ""
  },
  {
    "shortName": "split-horizontal",
    "character": "",
    "unicode": "EB56",
    "description": ""
  },
  {
    "shortName": "split-vertical",
    "character": "",
    "unicode": "EB57",
    "description": ""
  },
  {
    "shortName": "squirrel",
    "character": "",
    "unicode": "EB58",
    "description": ""
  },
  {
    "shortName": "star-empty",
    "character": "",
    "unicode": "EA6A",
    "description": ""
  },
  {
    "shortName": "star-full",
    "character": "",
    "unicode": "EB59",
    "description": ""
  },
  {
    "shortName": "star-half",
    "character": "",
    "unicode": "EB5A",
    "description": ""
  },
  {
    "shortName": "stop-circle",
    "character": "",
    "unicode": "EBA5",
    "description": ""
  },
  {
    "shortName": "surround-with",
    "character": "",
    "unicode": "EC24",
    "description": ""
  },
  {
    "shortName": "symbol-array",
    "character": "",
    "unicode": "EA8A",
    "description": ""
  },
  {
    "shortName": "symbol-boolean",
    "character": "",
    "unicode": "EA8F",
    "description": ""
  },
  {
    "shortName": "symbol-class",
    "character": "",
    "unicode": "EB5B",
    "description": ""
  },
  {
    "shortName": "symbol-color",
    "character": "",
    "unicode": "EB5C",
    "description": ""
  },
  {
    "shortName": "symbol-constant",
    "character": "",
    "unicode": "EB5D",
    "description": ""
  },
  {
    "shortName": "symbol-enum-member",
    "character": "",
    "unicode": "EB5E",
    "description": ""
  },
  {
    "shortName": "symbol-enum",
    "character": "",
    "unicode": "EA95",
    "description": ""
  },
  {
    "shortName": "symbol-event",
    "character": "",
    "unicode": "EA86",
    "description": ""
  },
  {
    "shortName": "symbol-field",
    "character": "",
    "unicode": "EB5F",
    "description": ""
  },
  {
    "shortName": "symbol-interface",
    "character": "",
    "unicode": "EB61",
    "description": ""
  },
  {
    "shortName": "symbol-key",
    "character": "",
    "unicode": "EA93",
    "description": ""
  },
  {
    "shortName": "symbol-keyword",
    "character": "",
    "unicode": "EB62",
    "description": ""
  },
  {
    "shortName": "symbol-method-arrow",
    "character": "",
    "unicode": "EC41",
    "description": ""
  },
  {
    "shortName": "symbol-method",
    "character": "",
    "unicode": "EA8C",
    "description": ""
  },
  {
    "shortName": "symbol-misc",
    "character": "",
    "unicode": "EB63",
    "description": ""
  },
  {
    "shortName": "symbol-namespace",
    "character": "",
    "unicode": "EA8B",
    "description": ""
  },
  {
    "shortName": "symbol-numeric",
    "character": "",
    "unicode": "EA90",
    "description": ""
  },
  {
    "shortName": "symbol-operator",
    "character": "",
    "unicode": "EB64",
    "description": ""
  },
  {
    "shortName": "symbol-parameter",
    "character": "",
    "unicode": "EA92",
    "description": ""
  },
  {
    "shortName": "symbol-property",
    "character": "",
    "unicode": "EB65",
    "description": ""
  },
  {
    "shortName": "symbol-ruler",
    "character": "",
    "unicode": "EA96",
    "description": ""
  },
  {
    "shortName": "symbol-snippet",
    "character": "",
    "unicode": "EB66",
    "description": ""
  },
  {
    "shortName": "symbol-string",
    "character": "",
    "unicode": "EB8D",
    "description": ""
  },
  {
    "shortName": "symbol-structure",
    "character": "",
    "unicode": "EA91",
    "description": ""
  },
  {
    "shortName": "symbol-variable",
    "character": "",
    "unicode": "EA88",
    "description": ""
  },
  {
    "shortName": "sync-ignored",
    "character": "",
    "unicode": "EB9F",
    "description": ""
  },
  {
    "shortName": "sync",
    "character": "",
    "unicode": "EA77",
    "description": ""
  },
  {
    "shortName": "table",
    "character": "",
    "unicode": "EBB7",
    "description": ""
  },
  {
    "shortName": "tag",
    "character": "",
    "unicode": "EA66",
    "description": ""
  },
  {
    "shortName": "target",
    "character": "",
    "unicode": "EBF8",
    "description": ""
  },
  {
    "shortName": "tasklist",
    "character": "",
    "unicode": "EB67",
    "description": ""
  },
  {
    "shortName": "telescope",
    "character": "",
    "unicode": "EB68",
    "description": ""
  },
  {
    "shortName": "terminal-bash",
    "character": "",
    "unicode": "EBCA",
    "description": ""
  },
  {
    "shortName": "terminal-cmd",
    "character": "",
    "unicode": "EBC4",
    "description": ""
  },
  {
    "shortName": "terminal-debian",
    "character": "",
    "unicode": "EBC5",
    "description": ""
  },
  {
    "shortName": "terminal-linux",
    "character": "",
    "unicode": "EBC6",
    "description": ""
  },
  {
    "shortName": "terminal-powershell",
    "character": "",
    "unicode": "EBC7",
    "description": ""
  },
  {
    "shortName": "terminal-tmux",
    "character": "",
    "unicode": "EBC8",
    "description": ""
  },
  {
    "shortName": "terminal-ubuntu",
    "character": "",
    "unicode": "EBC9",
    "description": ""
  },
  {
    "shortName": "terminal",
    "character": "",
    "unicode": "EA85",
    "description": ""
  },
  {
    "shortName": "text-size",
    "character": "",
    "unicode": "EB69",
    "description": ""
  },
  {
    "shortName": "three-bars",
    "character": "",
    "unicode": "EB6A",
    "description": ""
  },
  {
    "shortName": "thumbsdown-filled",
    "character": "",
    "unicode": "EC13",
    "description": ""
  },
  {
    "shortName": "thumbsdown",
    "character": "",
    "unicode": "EB6B",
    "description": ""
  },
  {
    "shortName": "thumbsup-filled",
    "character": "",
    "unicode": "EC14",
    "description": ""
  },
  {
    "shortName": "thumbsup",
    "character": "",
    "unicode": "EB6C",
    "description": ""
  },
  {
    "shortName": "tools",
    "character": "",
    "unicode": "EB6D",
    "description": ""
  },
  {
    "shortName": "trash",
    "character": "",
    "unicode": "EA81",
    "description": ""
  },
  {
    "shortName": "triangle-down",
    "character": "",
    "unicode": "EB6E",
    "description": ""
  },
  {
    "shortName": "triangle-left",
    "character": "",
    "unicode": "EB6F",
    "description": ""
  },
  {
    "shortName": "triangle-right",
    "character": "",
    "unicode": "EB70",
    "description": ""
  },
  {
    "shortName": "triangle-up",
    "character": "",
    "unicode": "EB71",
    "description": ""
  },
  {
    "shortName": "twitter",
    "character": "",
    "unicode": "EB72",
    "description": ""
  },
  {
    "shortName": "type-hierarchy-sub",
    "character": "",
    "unicode": "EBBA",
    "description": ""
  },
  {
    "shortName": "type-hierarchy-super",
    "character": "",
    "unicode": "EBBB",
    "description": ""
  },
  {
    "shortName": "type-hierarchy",
    "character": "",
    "unicode": "EBB9",
    "description": ""
  },
  {
    "shortName": "unfold",
    "character": "",
    "unicode": "EB73",
    "description": ""
  },
  {
    "shortName": "ungroup-by-ref-type",
    "character": "",
    "unicode": "EB98",
    "description": ""
  },
  {
    "shortName": "unlock",
    "character": "",
    "unicode": "EB74",
    "description": ""
  },
  {
    "shortName": "unmute",
    "character": "",
    "unicode": "EB75",
    "description": ""
  },
  {
    "shortName": "unverified",
    "character": "",
    "unicode": "EB76",
    "description": ""
  },
  {
    "shortName": "variable-group",
    "character": "",
    "unicode": "EBB8",
    "description": ""
  },
  {
    "shortName": "verified-filled",
    "character": "",
    "unicode": "EBE9",
    "description": ""
  },
  {
    "shortName": "verified",
    "character": "",
    "unicode": "EB77",
    "description": ""
  },
  {
    "shortName": "versions",
    "character": "",
    "unicode": "EB78",
    "description": ""
  },
  {
    "shortName": "vm-active",
    "character": "",
    "unicode": "EB79",
    "description": ""
  },
  {
    "shortName": "vm-connect",
    "character": "",
    "unicode": "EBA9",
    "description": ""
  },
  {
    "shortName": "vm-outline",
    "character": "",
    "unicode": "EB7A",
    "description": ""
  },
  {
    "shortName": "vm-running",
    "character": "",
    "unicode": "EB7B",
    "description": ""
  },
  {
    "shortName": "vm",
    "character": "",
    "unicode": "EA7A",
    "description": ""
  },
  {
    "shortName": "vr",
    "character": "",
    "unicode": "EC18",
    "description": ""
  },
  {
    "shortName": "vscode-insiders",
    "character": "",
    "unicode": "EC2A",
    "description": ""
  },
  {
    "shortName": "vscode",
    "character": "",
    "unicode": "EC29",
    "description": ""
  },
  {
    "shortName": "wand",
    "character": "",
    "unicode": "EBCF",
    "description": ""
  },
  {
    "shortName": "warning",
    "character": "",
    "unicode": "EA6C",
    "description": ""
  },
  {
    "shortName": "watch",
    "character": "",
    "unicode": "EB7C",
    "description": ""
  },
  {
    "shortName": "whitespace",
    "character": "",
    "unicode": "EB7D",
    "description": ""
  },
  {
    "shortName": "whole-word",
    "character": "",
    "unicode": "EB7E",
    "description": ""
  },
  {
    "shortName": "window",
    "character": "",
    "unicode": "EB7F",
    "description": ""
  },
  {
    "shortName": "word-wrap",
    "character": "",
    "unicode": "EB80",
    "description": ""
  },
  {
    "shortName": "workspace-trusted",
    "character": "",
    "unicode": "EBC1",
    "description": ""
  },
  {
    "shortName": "workspace-unknown",
    "character": "",
    "unicode": "EBC3",
    "description": ""
  },
  {
    "shortName": "workspace-untrusted",
    "character": "",
    "unicode": "EBC2",
    "description": ""
  },
  {
    "shortName": "zoom-in",
    "character": "",
    "unicode": "EB81",
    "description": ""
  },
  {
    "shortName": "zoom-out",
    "character": "",
    "unicode": "EB82",
    "description": ""
  }
];

export default allIcons;